# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/protobuf/channel.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!meshtastic/protobuf/channel.proto\x12\x13meshtastic.protobuf\"\xc1\x01\n\x0f\x43hannelSettings\x12\x17\n\x0b\x63hannel_num\x18\x01 \x01(\rB\x02\x18\x01\x12\x0b\n\x03psk\x18\x02 \x01(\x0c\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\n\n\x02id\x18\x04 \x01(\x07\x12\x16\n\x0euplink_enabled\x18\x05 \x01(\x08\x12\x18\n\x10\x64ownlink_enabled\x18\x06 \x01(\x08\x12<\n\x0fmodule_settings\x18\x07 \x01(\x0b\x32#.meshtastic.protobuf.ModuleSettings\">\n\x0eModuleSettings\x12\x1a\n\x12position_precision\x18\x01 \x01(\r\x12\x10\n\x08is_muted\x18\x02 \x01(\x08\"\xb3\x01\n\x07\x43hannel\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x36\n\x08settings\x18\x02 \x01(\x0b\x32$.meshtastic.protobuf.ChannelSettings\x12/\n\x04role\x18\x03 \x01(\x0e\x32!.meshtastic.protobuf.Channel.Role\"0\n\x04Role\x12\x0c\n\x08\x44ISABLED\x10\x00\x12\x0b\n\x07PRIMARY\x10\x01\x12\r\n\tSECONDARY\x10\x02\x42\x63\n\x14org.meshtastic.protoB\rChannelProtosZ\"github.com/meshtastic/go/generated\xaa\x02\x14Meshtastic.Protobufs\xba\x02\x00\x62\x06proto3')



_CHANNELSETTINGS = DESCRIPTOR.message_types_by_name['ChannelSettings']
_MODULESETTINGS = DESCRIPTOR.message_types_by_name['ModuleSettings']
_CHANNEL = DESCRIPTOR.message_types_by_name['Channel']
_CHANNEL_ROLE = _CHANNEL.enum_types_by_name['Role']
ChannelSettings = _reflection.GeneratedProtocolMessageType('ChannelSettings', (_message.Message,), {
  'DESCRIPTOR' : _CHANNELSETTINGS,
  '__module__' : 'meshtastic.protobuf.channel_pb2'
  # @@protoc_insertion_point(class_scope:meshtastic.protobuf.ChannelSettings)
  })
_sym_db.RegisterMessage(ChannelSettings)

ModuleSettings = _reflection.GeneratedProtocolMessageType('ModuleSettings', (_message.Message,), {
  'DESCRIPTOR' : _MODULESETTINGS,
  '__module__' : 'meshtastic.protobuf.channel_pb2'
  # @@protoc_insertion_point(class_scope:meshtastic.protobuf.ModuleSettings)
  })
_sym_db.RegisterMessage(ModuleSettings)

Channel = _reflection.GeneratedProtocolMessageType('Channel', (_message.Message,), {
  'DESCRIPTOR' : _CHANNEL,
  '__module__' : 'meshtastic.protobuf.channel_pb2'
  # @@protoc_insertion_point(class_scope:meshtastic.protobuf.Channel)
  })
_sym_db.RegisterMessage(Channel)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.meshtastic.protoB\rChannelProtosZ\"github.com/meshtastic/go/generated\252\002\024Meshtastic.Protobufs\272\002\000'
  _CHANNELSETTINGS.fields_by_name['channel_num']._options = None
  _CHANNELSETTINGS.fields_by_name['channel_num']._serialized_options = b'\030\001'
  _CHANNELSETTINGS._serialized_start=59
  _CHANNELSETTINGS._serialized_end=252
  _MODULESETTINGS._serialized_start=254
  _MODULESETTINGS._serialized_end=316
  _CHANNEL._serialized_start=319
  _CHANNEL._serialized_end=498
  _CHANNEL_ROLE._serialized_start=450
  _CHANNEL_ROLE._serialized_end=498
# @@protoc_insertion_point(module_scope)
